In [1]:
import os;

In [6]:
import pandas as pd
pd.read_parquet('test.parquet', engine='pyarrow')

,timestamp,symbol,bid_price,bid_size,ask_price,ask_size,market_period,trade_price,trade_volume,type
0,2024-01-22 05:04:15,KPL,15.05,112.0,15.15,18.0,,NaN,NaN,Quote
1,2024-01-22 08:30:19,KPL,15.05,112.0,15.20,82.0,COCA,NaN,NaN,Quote
2,2024-01-22 08:30:19,KPL,15.05,112.0,15.15,18.0,COCA,NaN,NaN,Quote
3,2024-01-22 08:30:22,KPL,15.00,502.0,15.15,18.0,COCA,NaN,NaN,Quote
4,2024-01-22 08:30:22,KPL,15.05,112.0,15.15,18.0,COCA,NaN,NaN,Quote
...,...,...,...,...,...,...,...,...,...,...
645580,2024-01-22 16:24:00,BBT,NaN,NaN,NaN,NaN,None,10.55,150.0,Trade
645581,2024-01-22 16:24:00,BBT,NaN,NaN,NaN,NaN,None,10.50,10.0,Trade
645582,2024-01-22 16:24:00,BBT,NaN,NaN,NaN,NaN,None,10.50,20.0,Trade
645583,2024-01-22 16:24:00,BBT,NaN,NaN,NaN,NaN,None,10.50,80.0,Trade
645584,2024-01-22 16:50:00,BBT,10.50,815.0,10.70,5.0,CLCA,NaN,NaN,Quote

In [5]:


dir(aggregator)

['Aggregate',
 'Aggregator',
 'Filter',
 'NamedTuple',
 'NoopFilter',
 'Quote',
 'Trade',
 'WallClockSliceSchedule',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'abstractmethod',
 'pd',
 'time',
 'timedelta']

In [1]:
import sys
sys.path.append('/Users/annakapka/code/rust/marketdata/python')
import aggregator
import filters


class testAggregate(aggregator.Aggregate):
    def __init__(self):
        self.index = 0
        self.trade_index=0
    
    def on_quote(self, quote):
        if self.index < 10:
            self.index += 1
            print(f"Quote just happened {quote}")
    
    def on_trade(self, trade):
        if self.trade_index < 10:
            self.trade_index += 1
            print(f"Trade just happened {trade}")


agg = aggregator.Aggregator("test.parquet", filters.SymbolFilter('PKO'))
agg.registerAggregate(testAggregate())
agg.run()

#agg.getAggregates()

Quote just happened Quote(timestamp=Timestamp('2024-01-22 05:04:15'), symbol='PKO', bid_price=49.33, bid_size=1.0, ask_price=49.78, ask_size=92.0, market_period='', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:00'), symbol='PKO', bid_price=49.33, bid_size=1.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:01'), symbol='PKO', bid_price=49.43, bid_size=30.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:01'), symbol='PKO', bid_price=49.78, bid_size=4.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:06'), symbol='PKO', bid_price=49.78, bid_size=14.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:09'), symbol='PKO', bid_price=49.78, bid_size=19.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:10'), symbol='PKO', bid_price=49.58, bid_size=81.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:10'), symbol='PKO', bid_price=49.78, bid_size=19.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:10'), symbol='PKO', bid_price=49.78, bid_size=21.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Quote just happened Quote(timestamp=Timestamp('2024-01-22 08:30:10'), symbol='PKO', bid_price=49.78, bid_size=21.0, ask_price=49.41, ask_size=374.0, market_period='COCA', type='Quote')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=64.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=26.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=17.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=3.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=1.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=44.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=20.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=10.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=17.0, type='Trade')
Trade just happened Trade(timestamp=Timestamp('2024-01-22 09:00:00'), symbol='PKO', trade_price=49.98, trade_volume=3.0, type='Trade')